In [23]:
import numpy as np

### Creating numpy array

In [24]:
ar1=np.array([3,5,6,8,10])
print(ar1)
print(type(ar1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


### Creating two dimensional array

In [25]:
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print(type(arr_2))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### To check dimensions of array

In [26]:
print(f"{arr_2.ndim} dimensions")

2 dimensions


### create 3 dimensional array

In [27]:
array_3d=np.array([[[1,2,3],[4,5,6]], [[6,7,8],[9,10,11]]])
print(f"{array_3d.ndim} dimensional array")
array_3d

3 dimensional array


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [28]:
ar100=np.arange(2,101,2)
ar100

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [29]:
### linspace
ar2=np.linspace(1,10,10)
print(ar2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Creating zero, ones and identity matrix

In [30]:
ar_0=np.zeros((8,8), dtype=int)
print(ar_0)
ar_1=np.ones((7), dtype=int)
ar_iden=np.eye(8)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


# to check shape of any array

In [31]:
print(f"{array_3d.shape} is the size of array_3d")

(2, 2, 3) is the size of array_3d


# operations on arrays

In [32]:
a1=np.array([[4,5,7],[1,2,3]])
a2=np.array([[8,9,1],[1,2,3]])
print(a1*a2)

[[32 45  7]
 [ 1  4  9]]


### matrix operations

In [42]:
a1d=np.array([[4,5,7],[1,2,3],[6,7,8]])
a2d=np.array([[8,9,1],[1,2,3],[2,3,4]])
print(a1d @ a2d)

[[51 67 47]
 [16 22 19]
 [71 92 59]]
