In [1]:
import numpy as np

# concatenation in numpy

In [ ]:
ar1=np.array([1,2,3,4])
ar2=np.array([2,2,2,2])
ar3=np.concatenate((ar1,ar2))
print(ar3) # axis:1 concatenation

[1 2 3 4 2 2 2 2]
[1 2 3 4 2 2 2 2]


# concatenation in 2d array in axis=0

In [13]:
a1=np.array([[1,2,3,4],[5,3,4,5]])
a2=np.array([[5,6,7,8],[6,7,8,9]])
a3=np.concatenate((a1,a2), axis=0)
print(a3)  #axis=0 concatenation

[[1 2 3 4]
 [5 3 4 5]
 [5 6 7 8]
 [6 7 8 9]]


# concatenation in 2d array in axis=1

In [15]:
a1=np.array([[1,2,3,4],[5,3,4,5]])
a2=np.array([[5,6,7,8],[6,7,8,9]])
a3=np.concatenate((a1,a2), axis=1)
print(a3)  

[[1 2 3 4 5 6 7 8]
 [5 3 4 5 6 7 8 9]]


# concatenating an array to either of the axis

In [ ]:
a1=np.array([[1,2,3,4],[5,3,4,5]])
a2=np.array([[5,6,7,8],[6,7,8,9]])
a4=np.concatenate((a1,a2),axis=1)    # for adding value to the side of the array
print(a4)
a5=np.concatenate((a1,a2),axis=0)   # for adding value below the existing array
print(a5)

[[1 2 3 4 5 6 7 8]
 [5 3 4 5 6 7 8 9]]
[[1 2 3 4]
 [5 3 4 5]
 [5 6 7 8]
 [6 7 8 9]]


# vstack and hstack

In [19]:
a3= np.vstack((a1,a2))
print(a3)
a7=np.hstack((a1,a2))
print(a7)

[[1 2 3 4]
 [5 3 4 5]
 [5 6 7 8]
 [6 7 8 9]]
[[1 2 3 4 5 6 7 8]
 [5 3 4 5 6 7 8 9]]


In [26]:
vsar=np.array([[1,2,3],[2,3,3]])
hsar=np.array([[4,5,6]])
p=np.vstack((vsar,hsar))
p

array([[1, 2, 3],
       [2, 3, 3],
       [4, 5, 6]])