In [20]:
import numpy as np

### Creating numpy array

In [21]:
ar1=np.array([3,5,6,8,10])
print(ar1)
print(type(ar1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


### Creating two dimensional array

In [22]:
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print(type(arr_2))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### To check dimensions of array

In [23]:
print(f"{arr_2.ndim} dimensions")

2 dimensions


### create 3 dimensional array

In [24]:
array_3d=np.array([[[1,2,3],[4,5,6]], [[6,7,8],[9,10,11]]])
print(f"{array_3d.ndim} dimensional array")
array_3d

3 dimensional array


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
ar100=np.arange(2,101,2)
ar100

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [26]:
### linspace
ar2=np.linspace(1,10,10)
print(ar2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# Creating zero, ones and identity matrix

In [27]:
ar_0=np.zeros((8,8), dtype=int)
print(ar_0)
ar_1=np.ones((7), dtype=int)
ar_iden=np.eye(8)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


# to check shape of any array

In [28]:
print(f"{array_3d.shape} is the size of array_3d")

(2, 2, 3) is the size of array_3d


# operations on arrays

In [29]:
a1=np.array([[4,5,7],[1,2,3]])
a2=np.array([[8,9,1],[1,2,3]])
print(a1*a2)

[[32 45  7]
 [ 1  4  9]]


### matrix operations

In [30]:
a1d=np.array([[4,5,7],[1,2,3],[6,7,8]])
a2d=np.array([[8,9,1],[1,2,3],[2,3,4]])
print(a1d @ a2d)

[[51 67 47]
 [16 22 19]
 [71 92 59]]


# creating multi-dimensional arrays

In [31]:
multarr1=np.array([2,3,4,5], ndmin=5)
print(multarr1)
print(multarr1.shape)

[[[[[2 3 4 5]]]]]
(1, 1, 1, 1, 4)


# operations in array

In [32]:
#vectorization in numpy array

array1= np.array([4,5,6,7])
print(array1+10)
print(array1 //2)

[14 15 16 17]
[2 2 3 3]


# indexing in numpy array

In [33]:
print(array1[1])

# in two-dimensional array

array2= np.array([[1,2,3,4],[2,4,5,6],[1,3,1,2]])
print(array2)
print(array2[1][3])    # [1] is row and [3] is column

5
[[1 2 3 4]
 [2 4 5 6]
 [1 3 1 2]]
6


# slicing numpy array

In [34]:
print(array2[1:3,1:3])

[[4 5]
 [3 1]]


# reshaping array

In [35]:
array2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"{array2d.shape} is the shape of array 2d ")
rearr2=array2d.reshape(1,12)
rearr2.ndim
rearr2_1d=array2d.reshape(12)
rearr2_1d.ndim
# rearr5=rearr2_1d.reshape(5,3)cant happen because number of elements dont match
rearr=rearr2_1d.reshape(2,6)
re2=rearr2_1d.reshape(2,3,2)
print(rearr)
print(re2)

(3, 4) is the shape of array 2d 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# to store numbers from 1 to 100 in a 2D array in the shape (5,20)

In [39]:
arrnat= np.arange(1,101)
arnat=arrnat.reshape(5,20)
print(arnat)
print(arnat.ndim)
print(arnat.shape)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]
2
(5, 20)


# 