In [2]:
import numpy as np

In [3]:
a1=np.linspace(-np.pi,np.pi,10, dtype=float)
a1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [4]:
sin_value= np.sin(a1)
rounded_val=np.round(sin_value,5)
print(rounded_val)

[-0.      -0.64279 -0.98481 -0.86603 -0.34202  0.34202  0.86603  0.98481
  0.64279  0.     ]


# using mean in numpy array

In [5]:
am=np.array([1,5,6,7])
mean=np.mean(am)
mean

np.float64(4.75)

# mean in 2d array

In [8]:
a2=np.array([[1,2,3,4],[5,6,7,8],
             [9,17,11,1]])
mean=np.mean(a2,)
mean
mean1=np.mean(a2, axis=0)
print(mean1)
mean2=np.mean(a2, axis=1)
print(mean2)

[5.         8.33333333 7.         4.33333333]
[2.5 6.5 9.5]
